
spring:
  datasource:
    url: jdbc:mysql://10.0.0.245:3306/time-block?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678

javax:
  persistence:
    schema-generation:
      scripts:
        action: drop-and-create
#        create-target:
#        drop-target:
        create-source: metadata
        drop-source: metadata